urllib.request does not exist in py27
build failed with error:
```
File "/home/travis/build/danielhrisca/asammdf/test/test_mdf.py", line 7, in <module>

    import urllib.request

ImportError: No module named request
```