Update mdf_common.py
typing error leads to
AttributeError: 'MDF4' object has no attribute '_raise_on_multiple_occurences'
just one 'l' missing
→ self._raise_on_multiple_occurrences instead of
→ self._raise_on_multiple_occurrences

Sorry for the inconvenience, there were actually two typos in the call and it occured two times in the file, didn't realize that before